### ISSUE TITLE
Show Release-Number

### ISSUE THREAD

**Issue by osmvermesser** [IpswichMapper/SwiftAddress#11]
It would bei helpful to show the current release-number in pulldown or other.

**Comment by IpswichMapper** [comment]
I think a good place for info like this would be in the navigation drawer. Android allows you to easily create headers in navigation drawers, I'll add that. Only thing is if I were to create a header a SwiftAddress logo would be nice. However I don't know what  logoto do and I not good at graphic design.

**Comment by IpswichMapper** [comment]
Added a navigation header. Do you like it?

![Screenshot_20210228-113008_SwiftAddress](https://user-images.githubusercontent.com/72318451/109416862-98d56f80-79b8-11eb-8e78-ec452c413678.png)

![Screenshot_20210228-113029_SwiftAddress](https://user-images.githubusercontent.com/72318451/109416860-983cd900-79b8-11eb-80c1-cd45b17cf035.png)

**Comment by MaggusK** [comment]
perfect!

**Comment by stephan75** [comment]
So this issue can be closed?

**Comment by IpswichMapper** [comment]
Sorry for my inactiveness, I really haven't had much time to develop swiftaddress in the padt 2 weeks. I usually wait until I have made a new release containing the changes until I close the issue. Howevee like I said I haven't had time to create a new release.

**Comment by osmvermesser** [comment]
No Problem
   
  
  
   
  
  
   there are thinks in live with more important.
   
  
  
   
  
  
   regards Jan
   
  
  
   
    IpswichMapper ***@***.***> hat am 16.03.2021 22:44 geschrieben:
   
   
    
   
   
    
   
   Sorry for my inactiveness, I really haven't had much time to develop swiftaddress in the padt 2 weeks. I usually wait until I have made a new release containing the changes until I close the issue. Howevee like I said I haven't had time to create a new release.
   —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
  
  
   
  
  
   Mit freundlichen GrüßenJan Tappenbeck-----------------------------------OpenStreetMap (OSM) - das FREIE Kartenprojekthttp://www.openstreetmap.deTREFFPUNKTE einfach weitergeben mit OpenStreetMap.Einzelheiten hierzu finden Sie auf meinem Blog unter ...https://blog.tappenbeck.net/2013/11/26/openstreetmap-treffpunkte-einfach-weitergeben/OpenStreetMap mit (FEHLER)HINWEISEN unterstützenEinzelheiten hierzu finden Sie auf meinem Blog unter ...https://blog.tappenbeck.net/2013/12/13/openstreetmap-mit-wenigen-schritten-das-projekt-unterstuetzen/
   
   ... dann gibt es da noch die Modellbahn Spur Z - meine Link-Tipps finden sich unter
   https://blog.tappenbeck.net/2015/02/19/linkliste-modellbahn-spur-z-co/

**Comment by IpswichMapper** [comment]
Will be in new release coming in a few hours
