### ISSUE TITLE
Toggle switch to display house numbers

### ISSUE THREAD

**Issue by BrackoNe** [IpswichMapper/SwiftAddress#12]
This one is enhancement.

It would be nice to have a toggle switch to turn on/off house numbers. Sometimes, when you go back and forth, it is hard to remember which of the house numbers you've already entered (especially when you have a blank map in front of you).

In addition to that: It would be great if you implement the **edit function** of the house numbers since now we have to completely remove the house number (if you remember which you have to remove it) and to re-add it.

**Comment by IpswichMapper** [comment]
What exactly do you mean by this?

When you add a housenumber, you can already see it on the map. Why would you want to disable this?

**Comment by BrackoNe** [comment]
Not icons, but labels.

![image](https://user-images.githubusercontent.com/8583745/108714604-08abac00-751a-11eb-862f-17b289202367.png)
You do not know which of these is house number 223. That's what I'm referring to.

**Comment by IpswichMapper** [comment]
What do you mean? I can already see the information about the housenumber when you click on it.

![Screenshot_20210228-112737_SwiftAddress](https://user-images.githubusercontent.com/72318451/109416746-046b0d00-79b8-11eb-9ef7-5f7a5e74d0c7.png)

Do you want to be able to see the housenumber **without** clicking on the icon? That (I think) would be more difficult.

**Comment by BrackoNe** [comment]
I believe that the problem is in Dark mode.

![Uploading Screenshot_20210228-131307_SwiftAddress.jpg…]()

**Comment by BrackoNe** [comment]
I believe that the problem is in Dark mode.

![Screenshot_20210228-131307_SwiftAddress](https://user-images.githubusercontent.com/8583745/109418113-e9ec6000-79c6-11eb-9771-8fc213e42a15.jpg)

**Comment by IpswichMapper** [comment]
> I believe that the problem is in Dark mode.

Yes, I fixed that in this commit: https://github.com/IpswichMapper/SwiftAddress/commit/7861007a06cb6cd96ce6b52edde7295748ae7f36

**Comment by IpswichMapper** [comment]
As for editing the housenumber, I could change the text showing the housenumber to a textbox that can be edited.

**Comment by IpswichMapper** [comment]
@BrackoNe 

What is the issue, other than the one I fixed?

**Comment by IpswichMapper** [comment]
I don't exactly understand this issue, but I have added a new feature: It now shows housenumbers on top of the address icon. This will be available in the new update in a few hours.
