### ISSUE TITLE
wrong name when pick address-marker

### ISSUE THREAD

**Issue by osmvermesser** [IpswichMapper/SwiftAddress#16]
hi !

when you pick to existing marker there will ever show the name "test".

![swiftaddress_marker](https://user-images.githubusercontent.com/6803899/110155356-ca4da100-7de5-11eb-818e-badf51402b01.jpg)

regards jan

**Comment by IpswichMapper** [comment]
I believe this has been fixed in the latest release. (v0.2.1)

Try adding a new marker in that release, see what happens.

**Comment by IpswichMapper** [comment]
yes, I just downloaded the latest release and reinstalled it on my phone, this is no longer an issue.

**Comment by osmvermesser** [comment]
hi !
   
  
  
   
  
  
   i see current in 0.2.1 and want current to write.
   
  
  
   
  
  
   Jan
   
  
  
   
    IpswichMapper <notifications@github.com> hat am 05.03.2021 19:24 geschrieben:
   
   
    
   
   
    
   
   
   I believe this has been fixed in the latest release. (v0.2.1)
   Try adding a new marker in that release, see what happens.
   —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
  
  
   
  
  
   Mit freundlichen GrüßenJan Tappenbeck-----------------------------------OpenStreetMap (OSM) - das FREIE Kartenprojekthttp://www.openstreetmap.deTREFFPUNKTE einfach weitergeben mit OpenStreetMap.Einzelheiten hierzu finden Sie auf meinem Blog unter ...https://blog.tappenbeck.net/2013/11/26/openstreetmap-treffpunkte-einfach-weitergeben/OpenStreetMap mit (FEHLER)HINWEISEN unterstützenEinzelheiten hierzu finden Sie auf meinem Blog unter ...https://blog.tappenbeck.net/2013/12/13/openstreetmap-mit-wenigen-schritten-das-projekt-unterstuetzen/
   
   ... dann gibt es da noch die Modellbahn Spur Z - meine Link-Tipps finden sich unter
   https://blog.tappenbeck.net/2015/02/19/linkliste-modellbahn-spur-z-co/

**Comment by IpswichMapper** [comment]
>    i see current in 0.2.1 and want current to write.

What do you mean by this?
