### ISSUE TITLE
show housenumber on map

### ISSUE THREAD

**Issue by osmvermesser** [IpswichMapper/SwiftAddress#17]
to make better mapping on the ground it would be helpful to show the housenumber in the app like:

![number](https://user-images.githubusercontent.com/6803899/110161389-95454c80-7ded-11eb-82a3-e11cee9e6d48.png)

Jan

**Comment by IpswichMapper** [comment]
I wish to do this, but I think it might be complicated.

 It requires being able to make the icons zoom in and change size and also only showing the text related markers when you have zoomed in enough.

**Comment by BrackoNe** [comment]
Duplicare of the issue #12

**Comment by IpswichMapper** [comment]
Done
