### ISSUE TITLE
wish: add cancel-button in move dialog

### ISSUE THREAD

**Issue by osmvermesser** [IpswichMapper/SwiftAddress#18]
it would be nice to cancel the move action directly in this dialog

![cancel](https://user-images.githubusercontent.com/6803899/110161513-c02fa080-7ded-11eb-8202-5078a9fa8452.png)

current you click move and then cancel.

Jan

**Comment by IpswichMapper** [comment]
You can already cancel "moving the marker":

![example of moving the marker cancel button](https://user-images.githubusercontent.com/72318451/110161988-0254e400-7de6-11eb-8fa6-6edb7799669e.png)

If you want to close that box that shows up, you can simply tap on it.

**Comment by IpswichMapper** [comment]
What do you want to cancel? If you haven't pressed the move button, there is nothing to cancel. If you want to close the dialog, simply press on the text and it will go away. 

In future versions pressing on the map will also make it go away.

**Comment by osmvermesser** [comment]
I would like to end the function at the moment shown in my first picture.

Jan

**Comment by IpswichMapper** [comment]
> If you want to close the dialog, simply press on the text and it will go away.

**Comment by IpswichMapper** [comment]
Also, when you open that dialog, this does not start moving the marker. The marker only starts moving when you press the move button
