### ISSUE TITLE
Label location moves with zoom level

### ISSUE THREAD

**Issue by Dubs120** [IpswichMapper/SwiftAddress#2]
Hi! For a while, I'm looking for a light phone application to collect house numbers, since they are critically missing on OSM...

StreetComplete is'nt designed for, especially for France where streetnumbers are not always linked to the building.

So, I'm happy to discover this one tonight!

I've a little concern about house number label, since it is difficult to see where they are exactly located on the map, since they location depend on the Zoom level :
I located it with very accurate zoom level :
![photo_2021-01-24_21-59-56](https://user-images.githubusercontent.com/73911790/105643891-eaa74900-5e92-11eb-92fb-9b46d60b0f08.jpg)
Then, when I used a rear zoom : 
![photo_2021-01-24_21-59-47](https://user-images.githubusercontent.com/73911790/105643929-1c201480-5e93-11eb-9d42-7cc084dbad47.jpg)

I suppose the flag isn't centered on geolocation ? Is it possible to define the label centered on the geolocation?

**Comment by IpswichMapper** [comment]
sorry for the late response, I didn't have the right email set up.

Thanks for your report. This is due to marker placement in OSMdroid, I don't know why this happens. I have opened an issue in the OSMdroid repository:

https://github.com/osmdroid/osmdroid/issues/1688

Osmdroid is the map that you see in this aplication.

**Comment by Dubs120** [comment]
Hi @IpswichMapper happy to see you are still active on this topic!
| markerList.last().setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_BOTTOM)

I don't know how is actually working, but ANCHOR_BOTTOM sounds as an attachment of the bottom of the marker to the geolocation, isn't it?

Since marker is growing with zoom out (any option to prevent it?), the apparent location could be linked with it?

Anyway, I tried yesterday to use APK on site, but I never arrived to use my phone geolocation, and there were a lot of crashes. I will open another issue!

**Comment by IpswichMapper** [comment]
> I don't know how is actually working, but ANCHOR_BOTTOM sounds as an attachment of the bottom of the marker to the geolocation, isn't it?

Thank you!!!

Using this code fixed the issue:

```kotlin
markerList.last().setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_CENTER)
```

The problem is that the OSMdroid guide suggests ANCHOR_BOTTOM:

https://github.com/osmdroid/osmdroid/wiki/Markers,-Lines-and-Polygons#marker

Why is this? I have no clue. I will ask the osmdroid team why they have done that.
