### ISSUE TITLE
save data and clear in this moment

### ISSUE THREAD

**Issue by osmvermesser** [IpswichMapper/SwiftAddress#21]
when i work corret...

save the data by disk-symbol my current data will be delete.

i had to restore the data to add more information

wish:

functions like 
* clear all
* save as
* save - to be on the secret side of work

regards Jan

**Comment by IpswichMapper** [comment]
Data is meant to be saved after you have completely finished the survey outside and have gone back home. At that point, why do you still need the data on the map? 

Saving and deleting it means you can do a new survey without the old data. 

If you want to do any more edits simply use JOSM to do those types of edits (JOSM is much quicker)

I feel these extra options ("save", "save as", "clear") might make things more complicated

**Comment by osmvermesser** [comment]
I also like to save my data during the work process in order to counteract data loss, for example due to a crash or the like.

Nothing is more annoying than experiencing total data loss after a long day of recording.

reagards Jan

**Comment by IpswichMapper** [comment]
Data is saved in a database already. This database is saved in the app data, even if the app crashes. The data is only deleted if you uninstall the app or save a zip file.

 The only way to lose this is if the database gets corrupted somehow, or you go to "App Info" and "clear storage".

**Comment by IpswichMapper** [comment]
@osmvermesser 

I still don't understand the reason for this. Can you explain?

Like I said, the data is saved in the app as soon as you add a housenumber, you unless all the data of the app gets deleted, a crash won't affect anything.

I think, instead of this, I will iron out the "recover" feature and make sure that works perfectly
