### ISSUE TITLE
wish: top subbuttons - numpad

### ISSUE THREAD

**Issue by osmvermesser** [IpswichMapper/SwiftAddress#25]
If the sub-buttons (down) for the contacts are not yet planned differently, then the values ​​"d, e, f" are desirable there.

![2021-03-07_17h20_05](https://user-images.githubusercontent.com/6803899/110247848-92be3080-7f6e-11eb-82d7-c4874c3b43a2.png)

**Comment by IpswichMapper** [comment]
I have done it in a slightly different manner, but I have added d, e, f button.

It will be available in the new update coming in a few hours.
