### ISSUE TITLE
Bug: In dark mode the address can't be read in the speech bubble

### ISSUE THREAD

**Issue by MaggusK** [IpswichMapper/SwiftAddress#28]
When I turn my mobile to dark mode there is gray font on gray background, so it's impossible to read, which number/road point I tagged. See this screenshot:
![signal-2021-03-21-220302](https://user-images.githubusercontent.com/6929342/111921041-bdda7100-8a92-11eb-89d0-73bed47ae3c8.png)

**Comment by BrackoNe** [comment]
Confirm. Still present.

**Comment by IpswichMapper** [comment]
I have completely overhauled this thing. You can now edit housenumbers and streets directly in the infowindow
