### ISSUE TITLE
Keypad colours

### ISSUE THREAD

**Issue by GeorgeHoneywood** [IpswichMapper/SwiftAddress#3]
Hey, I've found a problem with the keypad on my phone, there is very little contrast between the text and the background.

My first thought is that it might be to do with dark theme on my phone, but turning it off didn't seem to fix it. Let me know if you have any thoughts :)

![Screenshot_20210126-102555_SwiftAddress](https://user-images.githubusercontent.com/25514836/105834546-8aafc000-5fc2-11eb-88e2-87f4cd68f4df.png)

**Comment by IpswichMapper** [comment]
What version and type of android do you use?

Have you checked all the styling options? For example, on light mode, everything works fine for me, however, when I change it to dark, I get the exact same as you. Maybe your phone has a built in dark mode that can't be disabled or something.

![Screenshot_20210126-215247_LineageOS_Settings](https://user-images.githubusercontent.com/72318451/105910436-da24d900-6020-11eb-9344-afb57ae01239.png)

I will fix the app for dark mode soon.

**Comment by IpswichMapper** [comment]
I've added dark mode support now:

![Screenshot_20210126-222948_SwiftAddress](https://user-images.githubusercontent.com/72318451/105914255-055df700-6026-11eb-8551-9f0aea9cb944.png)

Does it look ok?

**Comment by GeorgeHoneywood** [comment]
Yep, that looks excellent :)

I also appear to have found another issue, where if you move to a location that can't be geocoded (i.e. the sea) and open the keypad, the app will crash. You might want to make another issue for that though 😃

**Comment by IpswichMapper** [comment]
I swear I fixed that one... (It was caused by the fact that nominatim can't find any nearby street)

Maybe it's not in the latest release. Let me check

**Comment by IpswichMapper** [comment]
Yep, I have fixed it in this commit: https://github.com/IpswichMapper/SwiftAddress/commit/26684c503d501c17d2fd9b93251a97eae6ec29b9

But that was after the latest release.

I'll done quite a few commits since the last one, so I'll add a new release now.

**Comment by IpswichMapper** [comment]
Just added a new release that supports dark mode, fixed that bug and saves notes properly, here it is:

https://github.com/IpswichMapper/SwiftAddress/releases/tag/v0.1.3

**Comment by GeorgeHoneywood** [comment]
Excellent, I'll close this issue then :)

**Comment by IpswichMapper** [comment]
Check if the dark mode works for you

**Comment by GeorgeHoneywood** [comment]
> Check if the dark mode works for you

Yep, all works fine thank you.
