### ISSUE TITLE
Break: Update 0.2.1 -> 0.3.0  unable to start!

### ISSUE THREAD

**Issue by osmvermesser** [IpswichMapper/SwiftAddress#33]
after update the program will not start.

only new installation will helpfull.

other users have the same problem.

Jan

**Comment by IpswichMapper** [comment]
Another issue on this already been made (issue #31 ). Please check before creating duplicate issues
-- 


29 Mar 2021, 18:17 by ***@***.***:

**Comment by IpswichMapper** [comment]
Fixed: d2b542c72579e4ba7e0eec41a6cd7512d9e0d81f

when upgrading from 0.2.1 -> 0.3.1, it will work
