### ISSUE TITLE
Increments

### ISSUE THREAD

**Issue by zorque2009** [IpswichMapper/SwiftAddress#7]
It doesn't consider the increment setting. It will always increment by +2

**Comment by IpswichMapper** [comment]
Yes, this is a bug that I have fixed. HOWEVER, the fix is not in the latest release.

I'll add a new version soon with the fix.

Also, the increment button only affects long press on the homescreen, NOT the plus or minus buttons in the keypad.
3 Feb 2021, 12:37 by notifications@github.com:

**Comment by IpswichMapper** [comment]
fixed in new release, hopefully. Please reopen if fix doesn't work
