### ISSUE TITLE
Screen timeout

### ISSUE THREAD

**Issue by zorque2009** [IpswichMapper/SwiftAddress#8]
Would be nice to have a setting to keep the screen on while the app is running.

**Comment by IpswichMapper** [comment]
Sure, maybe ill add this in the future, but this would need to create a settings screen sothat options like that can be modified.

Currenly, though, how is the screen timing out for you? Surely when you add address numbers, you are constantly touching the screen, so how is screen timeout going to happen?

Thanks-- 
 

3 Feb 2021, 12:37 by notifications@github.com:

**Comment by IpswichMapper** [comment]
I added it:

https://github.com/IpswichMapper/SwiftAddress/commit/345b225c84d7af378fdf75dbe620b33ae7b3e81b

**Comment by IpswichMapper** [comment]
there is a new release up (version 0.2) with the bug fix included. Please reopen this issue if it doesn't work.
