### ISSUE TITLE
custom backgrounds

### ISSUE THREAD

**Issue by schablonski** [IpswichMapper/SwiftAddress#9]
I have a private webserver with a special slippymap for mapping. Please allow to switch to custom tile-servers for background-maps.

**Comment by IpswichMapper** [comment]
I haven't even implemented any tileservers other than the default OSM one yet. Once I have done that I will look into this.

**Comment by BrackoNe** [comment]
+1

This one would be useful! The app should either support the existing public tiles, e.g., Bing Aerial imagery, or an even better solution is to support custom tiles. You should be able to add it in the app's settings. Now I could see that building labels were missing on the OSM of the area that I surveyed, and it was tough to match the exact location of the address point.

**Comment by IpswichMapper** [comment]
Yes, I do have to ask though: what imageries to use and his to implement them. Currently the imagerieimageries don't seem to work. Fi you press the map icon near the top right you can see the imagery options. Currently I do have public transport map as an option however every time I try adding a map that inst osm-carto (default tiles), then I get an error saying clear text HTTP traffic is not allowed.

Also, some imageries, like mapbox want an api key, so I'd have to sign up or something to be able to use them.
--20 Feb 2021, 23:41 by notifications@github.com:

**Comment by BrackoNe** [comment]
Maybe it is the best solution to leave an option for custom imagery support.
That means once you click on the map icon, you do not need to show a new screen with two predefined buttons but try to make a finger-friendly dropdown list, or like it is in the Google Maps app (show a new floating menu to choose the imagery from).

I hope this helps.

**Comment by IpswichMapper** [comment]
Just added custom imagery in the latest release. However, it doesn't "store" the custom imagery. Every time you change the imagery, you have to manually add the custom imagery again. Feel free to close the issue if you feel that this is enough, however you can keep it open if you believe that the ability to save mutliple custom imageries should be added.

Also, it hasn't been tested fully yet, so it may not work perfectly.

**Comment by BrackoNe** [comment]
Thanks! I hope I will test it tomorrow, but it would definitely be a nice feature to save the imagery for later use.

**Comment by IpswichMapper** [comment]
@schablonski Thoughts?

**Comment by BrackoNe** [comment]
Tried. Works well. However, it would be great if the app can support both WMS and TMS services.

**Comment by IpswichMapper** [comment]
I don't know how WMS works, but I wrote a function to convert TMS to slippy map. Don't know why something like that doesn't already exist in the osmdroid library.

**Comment by IpswichMapper** [comment]
Okay, I have added the ability to remember imageries that you have added in the past. Imageries you have added in the past will show up as a list in the "Custom Imagery" dialog. You can delete items from that list or click on the item to autofill the custom imagery textbox with that item.
